name: editor acting

on:
  issues:
    types: [opened]
  issue_comment:
    types:
      - created
  pull_request:
    types: [opened, synchronize]
  pull_request_review_comment:
    types: [ created ]
  workflow_run:
    workflows: [ "reviewer acting"]
    types:
      - completed


jobs:
  respond:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print pull request number
      run: |  
        echo "Pull Request Number - ${{ github.event.pull_request.number }}"
        echo "Organization - ${{ github.repository_owner }}"
        echo "Repository Name - ${{ github.repository }}"

    - name: Print Job details
      run: |  
        echo "Run ID - ${{ github.run_id }}"
        echo "Run No - ${{ github.run_number }}"
        echo "Job    - ${{ github.job }}"
        echo "Job ID - ${{ github.job_id }}"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git-bob>=0.6.4
        

    - name: Run git-bob
      env:
        GIT_BOB_AGENT_NAME: "editor"
        GIT_BOB_ACCESS_GROUPS: "members,bot"
        GIT_BOB_LLM_NAME: "${{ secrets.GIT_BOB_LLM_NAME }}"
        ANTHROPIC_API_KEY: "${{ secrets.ANTHROPIC_API_KEY }}"
        GOOGLE_API_KEY: "${{ secrets.GOOGLE_API_KEY }}"
        OPENAI_API_KEY: "${{ secrets.OPENAI_API_KEY }}"
        GH_MODELS_API_KEY: "${{ secrets.GH_MODELS_API_KEY }}"
        GITHUB_API_KEY: "${{ secrets.GITHUB_TOKEN }}"
        GITHUB_RUN_ID: "${{ github.run_id }}"
        TWINE_USERNAME: "${{ secrets.TWINE_USERNAME }}"
        TWINE_PASSWORD: "${{ secrets.TWINE_PASSWORD }}"
        SYSTEM_MESSAGE: |
          You are the editor of a scientific blog and you take your job very seriously. 
          You use a discussion on a github pull-request for communicating with the author and a reviewer.
          When you receive a pull-request for reviewing, introduce yourself, confirm that you received the pull-requeest kindly, and say thanks to the author. 
          Let the author know how the procedure works: a reviewer will be asked to review and depending on the review, the pull-request may be accepted or not.
          If no reviewer has written anything yet, you ask the reviewer to review the document. You do this with the phrase "reviewer review this please." (exactly like this).
          If the discussion contains a comment from a reviewer, you summarize the review and the conclusion. Depending on the review and the conclusion, you decide if the pull-request should be accepted or not. Inform the author about the decision in this case.
          Again, be kind, communicate professionally and mae everyone (original author and reviewr) happy. Make the review process a great experience for all involved.
      run: |
        git-bob github-action ${{ github.repository }} ${{ github.event.pull_request.number }} ${{ github.event.issue.number }}
