name: editor acting

on:
  issues:
    types: [opened]
  issue_comment:
    types:
      - created
  pull_request:
    types: [opened, synchronize]
  pull_request_review_comment:
    types: [ created ]
  workflow_run:
    workflows: [ "reviewer1 acting", "reviewer2 acting", "reviewer3 acting" ]
    types:
      - completed  # This can be 'completed', 'success', or 'failure'


jobs:
  respond:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print pull request number
      run: |  
        echo "Pull Request Number - ${{ github.event.pull_request.number }}"
        echo "Organization - ${{ github.repository_owner }}"
        echo "Repository Name - ${{ github.repository }}"

    - name: Print Job details
      run: |  
        echo "Run ID - ${{ github.run_id }}"
        echo "Run No - ${{ github.run_number }}"
        echo "Job    - ${{ github.job }}"
        echo "Job ID - ${{ github.job_id }}"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git-bob
        

    - name: Run git-bob
      env:
        GIT_BOB_AGENT_NAME: "editor"
        GIT_BOB_LLM_NAME: "${{ secrets.GIT_BOB_LLM_NAME }}"
        ANTHROPIC_API_KEY: "${{ secrets.ANTHROPIC_API_KEY }}"
        GOOGLE_API_KEY: "${{ secrets.GOOGLE_API_KEY }}"
        OPENAI_API_KEY: "${{ secrets.OPENAI_API_KEY }}"
        GH_MODELS_API_KEY: "${{ secrets.GH_MODELS_API_KEY }}"
        GITHUB_API_KEY: "${{ secrets.GITHUB_TOKEN }}"
        GITHUB_RUN_ID: "${{ github.run_id }}"
        TWINE_USERNAME: "${{ secrets.TWINE_USERNAME }}"
        TWINE_PASSWORD: "${{ secrets.TWINE_PASSWORD }}"
        SYSTEM_MESSAGE: |
          You are the editor of a scientific blog and you take your job very serious. 
          You use a discussion on a github pull-request for communicating with the author and the reviewers.
          When you receive a pull-request for reviewing, introduce yourself, confirm that you received the pull-requeest kindly, and say thanks to the author. 
          Let the author know how the procedure works: reviewers will be asked to review and depending on the review, the pull-request may be accepted or not. 
          If no reviewer has written anything yet, you ask reviewer1 to review the document. You do this with the phrase "reviewer1 review this please.".
          If the discussion already contains a comment from "reviewer1", you go ahead and also ask "reviewer2" for their feedback, analogously to reviewer1.
          If the discussion already contains a comment from "reviewer2", you have two options:
          * If both reviewers suggest the same (acceptance or rejection of the text modification), you summarize the reviews and the conclusion.
          * Otherwise, you ask reviewer3 for their feedback, analogously to how how you asked reviewer1 and 2.
          If the discussion contains a comment from all three reviewers, you summarize the reviews and the conclusion.
          When concluding, make sure you tag the original author's github handle (given in the initial pull-request) so that they receive a notification.
      run: |
        git-bob github-action ${{ github.repository }} ${{ github.event.pull_request.number }} ${{ github.event.issue.number }}
