name: reviewer acting

on:
  workflow_run:
    workflows: [ "editor acting"]
    types:
      - completed

jobs:
  respond:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print pull request number
      run: |  
        echo "Pull Request Number - ${{ github.event.pull_request.number }}"
        echo "Organization - ${{ github.repository_owner }}"
        echo "Repository Name - ${{ github.repository }}"

    - name: Print Job details
      run: |  
        echo "Run ID - ${{ github.run_id }}"
        echo "Run No - ${{ github.run_number }}"
        echo "Job    - ${{ github.job }}"
        echo "Job ID - ${{ github.job_id }}"

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: 3.x

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install git-bob>=0.6.4
        

    - name: Run git-bob
      env:
        GIT_BOB_AGENT_NAME: "reviewer"
        GIT_BOB_ACCESS_GROUPS: "members,bot"
        GIT_BOB_LLM_NAME: "${{ secrets.GIT_BOB_LLM_NAME }}"
        ANTHROPIC_API_KEY: "${{ secrets.ANTHROPIC_API_KEY }}"
        GOOGLE_API_KEY: "${{ secrets.GOOGLE_API_KEY }}"
        OPENAI_API_KEY: "${{ secrets.OPENAI_API_KEY }}"
        GH_MODELS_API_KEY: "${{ secrets.GH_MODELS_API_KEY }}"
        GITHUB_API_KEY: "${{ secrets.GITHUB_TOKEN }}"
        GITHUB_RUN_ID: "${{ github.run_id }}"
        TWINE_USERNAME: "${{ secrets.TWINE_USERNAME }}"
        TWINE_PASSWORD: "${{ secrets.TWINE_PASSWORD }}"
        SYSTEM_MESSAGE: |
          You are reviewer of a scientific blog. 
          You use a discussion on a github pull-request for communicating with the editor. 
          If there are discussion contributions from other reviewers, ignore them.
          When writing a review, you always start with "# Review of <your name>" and you finish with "editor comment" (exactly like this) on a new line.
          In between comes your review. This is how you review:
          * You carefully read and understood the contribution sent in the pull-request.
          * You provide constructive feedback on the contribution.
          * You communicate very professionally.
          * If the contribution is a useful addition to the blog, you recommend the editor to accept it.
          * If not, you give advice on how to improve the contribution and recommend a major revision.

      run: |
        git-bob github-action ${{ github.repository }} ${{ github.event.pull_request.number }} ${{ github.event.issue.number }}
